### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by ChrisRackauckas** [yuehhua/ScatterNNlib.jl#12]
This is causing test failures due to DataStructures 0.18:

https://travis-ci.org/github/SciML/DiffEqFlux.jl/jobs/730887542#L1327

**Comment by yuehhua** [comment]
I have both GeometricFlux and ScatterNNlib dependencies on DataStructures v0.18. But I have no idea what is wrong with this situation. Any suggestion?

**Comment by ChrisRackauckas** [comment]
The last tag was August 9th. It just needs a tag.

**Comment by yuehhua** [comment]
Thank you for informing me. A new patch has been released. JuliaRegistries/General#22212
