### ISSUE TITLE
Semantics of scatter_add!() arguments

### ISSUE THREAD

**Issue by dfdx** [yuehhua/ScatterNNlib.jl#22]
From the docstring of `scatter_add!()`:

> The index of `xs` is corresponding to the index of `us` and the value of `xs` is
corresponding to the index of `ys`.

Which I read as if `xs` and `us` should have the same size. But the next line states that:

> The dimension of `us` must equal to one plus dimension of `xs`.

Generally, this is not an issue and I already wrapped it into a more convenient for [my use case](https://discourse.julialang.org/t/increment-elements-of-array-by-index/49694) form, adding a singleton dimension to `ys` and `xs`:

```julia
function my_scatter_add!(A::AbstractArray, v::AbstractArray, I...)
    II = collect(Iterators.product(I...))
    A2 = ScatterNNlib.scatter_add!(reshape(A, 1, size(A)...), reshape(v, 1, size(v)...), II)
    return dropdims(A2, dims=1)
end
```
But why do we actually need this additional dimension? What's the intuition behind `xs` and `us` having different sizes?

**Comment by yuehhua** [comment]
In general, there are some dimensions to operate on and some dimensions remain fixed. A scatter function for specifying which dimensions to operate on is not available now. A general version of allowing all dimensions to operate on is good for low-level operations. For the usage of GeometricFlux, first dimension is remained for fixed dimension.

**Comment by dfdx** [comment]
Thanks for clarification!
